# Config
spring.config.import=optional:file:.env[.properties]

# Application
spring.application.name=Edu-Track-Backend

# Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_batch_fetch_size=50
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.open-in-view=false


# Logging Levels
logging.level.root=INFO
logging.level.com.example.edutrackbackend=DEBUG
logging.level.com.zaxxer.hikari=INFO
logging.level.org.springframework.jdbc.datasource=INFO
logging.level.org.hibernate.orm.connections=INFO

# Logging File
logging.file.name=logs/app.log

# Logging Patterns
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n

# JWT
jwt.secret=${JWT_SECRET}

spring.docker.compose.enabled=false