package com.example.edutrackbackend.common.enums;

public enum ErrorCode {
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    REFRESH_TOKEN_INVALID,
    STUDENT_NOT_FOUND,
    DUPLICATE_STUDENT_NUMBER,
    SECTION_NOT_FOUND,
    TEACHER_NOT_FOUND,
    AUTH_FAILED,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
